version: '3'
services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/config
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery
      - celery-beat

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: project7
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123'

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config worker -l INFO
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A config beat -l INFO
    depends_on:
      - redis