# Generated by Django 4.2.5 on 2023-10-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-id'], 'verbose_name': 'habit', 'verbose_name_plural': 'habits'},
        ),
    ]
